imports:
  - { resource: forms.yml }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Shopsys\ShopBundle\Controller\:
    resource: '../../Controller/'
    public: true
    tags: ['controller.service_arguments']

  Shopsys\ShopBundle\Model\:
    resource: '../../Model/*/*{Facade,Factory}.php'

  Shopsys\ShopBundle\Form\Front\Order\DomainAwareOrderFlowFactory: ~

  Shopsys\FrameworkBundle\Model\Order\OrderFlowFactoryInterface: '@Shopsys\ShopBundle\Form\Front\Order\DomainAwareOrderFlowFactory'

  Shopsys\FrameworkBundle\Model\Article\ArticleFactoryInterface: '@Shopsys\ShopBundle\Model\Article\ArticleFactory'

  Shopsys\FrameworkBundle\Model\Article\ArticleDataFactory: '@Shopsys\ShopBundle\Model\Article\ArticleDataFactory'

  Shopsys\ShopBundle\Model\Category\CurrentCategoryResolver: